import { writeFileSync } from 'fs';
import { resolve } from 'path';
import { decodeKiwiPayload, encodeAsKiwiQuery} from './kiwi-url-utils';
import { generatePayloadTable } from './kiwi-payload';


function getOutputPath(): string {
    const args = process.argv.slice(2);
    if (args.length === 0) {
        throw new Error('Output path argument is missing.');
    }
    return resolve(args[0]);
}

function decodePayloadExample() {
   // DoubleHorizontal class
//     const encodedPayload = 'AQIBQVA4Sk5ONUxZQUJHVk1HS1kxQgACUTFOQ1dXUEc2RlowRE5JWEpCUQADBAFGUzAwRFhWMFQ5UjFYOUZKNFFFAAIBMDEgSVQtRVQgR2x1dAAAAVFZNVM4S01PNUhMSlVGMFAwMEsAAgAAATE1Qks0N0RDSU9GMVNMTFVXOVAAAgAAAUNCR0MwVTMwVlY5SlBSNjBUSlUAAgAABAEBAoLIE8eBUfRuA4Q0SBOEWBhNAAUBAUMyMzAwOTlEMDhSaWsAAAYBAQJGUzAwRFhWMFQ5UjFYOUZKNFFFAAN%2BAAAABAAACEc0STRHRkpYSkI5QVRaM1BUWDEACUxWREJKQVc4Qkk1WVNTMVFVQkcACgALAW5vbmUAAm5vbmUAAwEEAQACIzAwMDAwMAADyAEABQEBAiMwMDAwMDAAA8gBAAAAAVpJM1JSMEZYTDNIWVhHVkUyUzUAAkZZWTRPTTJMVTVKMFlPRjA3RFIAAwQBRlMwMERYVjBUOVIxWDlGSjRRRQACATAxIElULUVUIEdsdXQAAAFRWTVTOEtNTzVITEpVRjBQMDBLAAIAAAExNUJLNDdEQ0lPRjFTTExVVzlQAAIAAAFDQkdDMFUzMFZWOUpQUjYwVEpVAAIAAAQBAAKEUL8fg4IJfwOEoBqHhMQ92QQyTlFUSUU3VEFNUDhQUUFITzRQAAWBr6ZKgemsDoGggUeAktXoBgAHAAAFAAYBAQJGUzAwRFhWMFQ5UjFYOUZKNFFFAAN%2BAAAABAAACDRTVENTWkJYSFlPSTBKVVVBM00ACUxWREJKQVc4Qkk1WVNTMVFVQkcACgALAVRMT0tXQ0w5NVJVMDNEOVBFVEcAAlRGUUZMTkVQM1YyMjJZODhDNjQAAwEEAQACIzAwMDAwMAADyAEABQEBAiMwMDAwMDAAA8gBAAAAAgMA';
    // Single subclass
    // const encodedPayload = 'AQEBQVA4Sk5ONUxZQUJHVk1HS1kxQgACUTFOQ1dXUEc2RlowRE5JWEpCUQADBAFGUzAwRFhWMFQ5UjFYOUZKNFFFAAIAAAFRWTVTOEtNTzVITEpVRjBQMDBLAAIBMDAzIEw1LzYgSVQgVFBFLUVOVCBHbHV0AAABMTVCSzQ3RENJT0YxU0xMVVc5UAACAAABQ0JHQzBVMzBWVjlKUFI2MFRKVQACAAAEAQECgazGjoGWFSADhGpN%2FYRYGE0ABQEBQzIzMDA5OUQwOFJpawAABgEBAlFZNVM4S01PNUhMSlVGMFAwMEsAA34AAAAEAAAIRzRJNEdGSlhKQjlBVFozUFRYMQAJTFZEQkpBVzhCSTVZU1MxUVVCRwAKAAsBbm9uZQACbm9uZQADAQQBAAIjMDAwMDAwAAPIAQAFAQECIzAwMDAwMAADyAEAAAACAQA%3D';
    // Single class
    // const encodedPayload = `AQEBWkkzUlIwRlhMM0hZWEdWRTJTNQACQU5IM1VUUzZEUzkyWEJUT0U0SwADBQEyTlFUSUU3VEFNUDhQUUFITzRQAAIEQzU3Qkw2Si02Mzg4NTAuMDMAQzU3Qkw2Si02Mzg4NTAuMDQAQzU3Qkw2Si02Mzg4NTAuNjAAQzU3Qkw2Si02Mzg4NTAuNjkAAAFGUzAwRFhWMFQ5UjFYOUZKNFFFAAIAAAFRWTVTOEtNTzVITEpVRjBQMDBLAAIBMDAyIElUIEVQLUNMQSBHbHV0AAABMTVCSzQ3RENJT0YxU0xMVVc5UAACAAABQ0JHQzBVMzBWVjlKUFI2MFRKVQACAAAEAQACgpRZsIH%2BGmwDhZIGAYRkAToEMk5RVElFN1RBTVA4UFFBSE80UAAFgevbQYEFpwaBWBtJgLxj5AYBAAUBAUNjbmQyAAAGAQACQ2NuZDIAA34AAAAEAAV9vAOpgsoMCAb0BgAIRFRWTEUxWUdOVEpRTVdWTUtFVQAJTFZEQkpBVzhCSTVZU1MxUVVCRwAKAAACAQA%3D`;
    // Merfish with imputed genes
    const encodedPayload = 'AQIBQVA4Sk5ONUxZQUJHVk1HS1kxQgACUTFOQ1dXUEc2RlowRE5JWEpCUQADBAFGUzAwRFhWMFQ5UjFYOUZKNFFFAAIAAAFRWTVTOEtNTzVITEpVRjBQMDBLAAIBMDAxIENMQS1FUGQtQ1RYIENhcjMgR2x1dAAAATE1Qks0N0RDSU9GMVNMTFVXOVAAAgAAAUNCR0MwVTMwVlY5SlBSNjBUSlUAAgAABAEBAoEQgHiBlLBEA4OwgMuEWBhNAAUABgEBAlFZNVM4S01PNUhMSlVGMFAwMEsAA34AAAAEAAAIRzRJNEdGSlhKQjlBVFozUFRYMQAJTFZEQkpBVzhCSTVZU1MxUVVCRwAKAAsBbm9uZQACbm9uZQADAQQBAAIjMDAwMDAwAAPIAQAFAQECIzAwMDAwMAADyAEAAAABSzlKTjIzUDI0S1FDR0s5VTc1QQACU1kzU0xNTlBJRDNDNjhNR1M4VgADAAQBAAKEJEAdgyIvtwOEsKBthXYLCQQyTlFUSUU3VEFNUDhQUUFITzRQAAWB69tBgQWnBoFYG0mAvGPkBgAHAAAFAAYBAQJGUzAwRFhWMFQ5UjFYOUZKNFFFAAN%2BAAAABAAACDZNVDdVQzZFVFlFQ0JXRjUwUEsACUxWREJKQVc4Qkk1WVNTMVFVQkcACgALAW5vbmUAAm5vbmUAAwEEAQACIzAwMDAwMAADyAEABQEBAiMwMDAwMDAAA8gBAAAAAgMA'

    const decodedPayload = decodeKiwiPayload(encodedPayload);
    // const content = 'Hello from TypeScript with a custom output path!\n';
    const content = JSON.stringify(decodedPayload, null, 2);
    console.log('Decoded Payload:', content);
    // writeFileSync(getOutputPath(), content, 'utf8');
    // console.log(`File written to ${getOutputPath()}`);
}


// decodePayloadExample();
const JSON_FILE_PATH = resolve(__dirname, '../../src/dendrograms/CCN20230722.json');
generatePayloadTable(JSON_FILE_PATH, getOutputPath());
console.log('ABC url generation successfully completed!');